# Generated by Django 5.0.3 on 2024-03-19 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='contactno',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='register',
            old_name='gcontactno',
            new_name='gcontact',
        ),
    ]
