# Generated by Django 5.0.3 on 2024-03-20 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0002_rename_contactno_register_contact_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='register',
            new_name='capp_register',
        ),
    ]
