# Generated by Django 5.0.3 on 2024-03-20 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0003_rename_register_capp_register'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='capp_register',
            new_name='register',
        ),
    ]
