# Generated by Django 5.0.3 on 2024-03-21 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('capp', '0005_login'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='address',
        ),
        migrations.RemoveField(
            model_name='register',
            name='age',
        ),
        migrations.RemoveField(
            model_name='register',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='register',
            name='category',
        ),
        migrations.RemoveField(
            model_name='register',
            name='city',
        ),
        migrations.RemoveField(
            model_name='register',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='register',
            name='course',
        ),
        migrations.RemoveField(
            model_name='register',
            name='coursemode',
        ),
        migrations.RemoveField(
            model_name='register',
            name='date',
        ),
        migrations.RemoveField(
            model_name='register',
            name='dateofjoin',
        ),
        migrations.RemoveField(
            model_name='register',
            name='district',
        ),
        migrations.RemoveField(
            model_name='register',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='register',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='register',
            name='email',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gcontact',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='register',
            name='gname',
        ),
        migrations.RemoveField(
            model_name='register',
            name='maritalstatus',
        ),
        migrations.RemoveField(
            model_name='register',
            name='name',
        ),
        migrations.RemoveField(
            model_name='register',
            name='occupation',
        ),
        migrations.RemoveField(
            model_name='register',
            name='pin',
        ),
        migrations.RemoveField(
            model_name='register',
            name='post',
        ),
        migrations.RemoveField(
            model_name='register',
            name='qualification',
        ),
        migrations.RemoveField(
            model_name='register',
            name='whatsapp',
        ),
    ]
